services:
  web:
    image: charleslevesque/nv-ss-docker:latest
    restart: always
    env_file:
      - ./web.env
    networks:
      - main-net
    depends_on:
      - database

  database:
    image: mcr.microsoft.com/mssql/server:2019-CU12-ubuntu-20.04
    restart: always
    environment:
      ACCEPT_EULA: "Y"
    env_file:
      - ./database.env
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - main-net

volumes:
  db-data: {}

networks:
  main-net: {}
